// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/msecommerce_product_service/pkg"
	"github.com/msecommerce_product_service/pkg/adapter"
	"github.com/msecommerce_product_service/pkg/config"
	"github.com/msecommerce_product_service/pkg/db"
	"github.com/msecommerce_product_service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*pkg.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(c)
	if err != nil {
		return nil, err
	}
	productAdapter := adapter.NewProductAdapter(gormDB)
	productUsecase := usecase.NewProductUsecase(productAdapter)
	serverHTTP := pkg.NewServerHTTP(productUsecase)
	return serverHTTP, nil
}
