// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/msecommerce/cart_service/pkg"
	"github.com/msecommerce/cart_service/pkg/adapter"
	"github.com/msecommerce/cart_service/pkg/client"
	"github.com/msecommerce/cart_service/pkg/config"
	"github.com/msecommerce/cart_service/pkg/db"
	"github.com/msecommerce/cart_service/pkg/service"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*pkg.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(c)
	if err != nil {
		return nil, err
	}
	cartAdapter := adapter.NewCartAdapter(gormDB)
	productClient := client.NewProductClient(c)
	cartServiceServer := service.NewCartServiceServer(cartAdapter, productClient)
	serverHTTP := pkg.NewServerHTTP(cartServiceServer)
	return serverHTTP, nil
}
